version: '3.8'

services:
  # MySQL
  database:
    container_name: money-save-database
    image: mysql:8
    platform: 'linux/x86_64'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_USER=hoang
      - MYSQL_PASSWORD=12345678
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=money_save_database
    ports:
      - 3306:3306
    networks:
      - app-network

  # Redis
  redis:
    container_name: money-save-cache
    image: redis:alpine
    platform: 'linux/x86_64'
    ports:
      - 6379:6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
