version: '3.8'

services:
  # Server
  app:
    build: .
    command: node dist/main.js
    restart: unless-stopped
    env_file: .env.staging
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    depends_on:
      - database
    ports:
      - 4200:4200
    networks:
      - app-network

  # MySQL
  database:
    image: mysql/mysql-server:8.0.31-aarch64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_HOST=0.0.0.0
      - MYSQL_USER=hoang
      - MYSQL_PASSWORD=12345678
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=e_commerce_staging
    ports:
      - 3306:3306
    networks:
      - app-network

  # Redis
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
